=== AydinHassan/m2-cron-job-disable/etc/cron_modify.xsd
<?xml version="1.0" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="config">
        <xs:complexType>
            <xs:sequence>
                <xs:element minOccurs="0" maxOccurs="unbounded" name="group" type="group" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="group">
        <xs:sequence>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="remove_job" type="xs:string"/>
            <xs:element minOccurs="0" maxOccurs="unbounded" name="move_job" type="move_group"/>
        </xs:sequence>
        <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>
    <xs:complexType name="move_group">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="to_group" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== AydinHassan/m2-cron-job-disable/etc/cron_modify.xml
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="cron_modify.xsd">
    <group name="default">
        <remove_job>currency_rates_update</remove_job>
        <remove_job>backend_clean_cache</remove_job>
        <move_job to_group="index">backend_clean_cache</move_job>
    </group>
    <group name="nosto">
        <remove_job>disable-me3</remove_job>
        <remove_job>disable-me4</remove_job>
    </group>
</config>
